[package]
name = "hrdja_primjeri"
version = "0.1.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hrÄ‘a = { path = "../hrdja_proc_macro/" }
